version: '3'

services:

  nginx:
    image: nginx:latest
    networks:
      default:
        aliases:
          - hello.service.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/index.html:ro
      - ./workspace:/etc/nginx/certs/

  client-python:
    image: python:3
    volumes:
      - ./clients/client.py:/opt/client.py:ro
      - ./workspace:/security/
    command: "bash -c 'cd /opt/; pip install requests; python client.py'"

  client-js:
    image: node:15
    volumes:
      - ./clients/client.js:/opt/client.js:ro
      - ./workspace:/security/
    command: "bash -c 'cd /opt/; node client.js'"