version: '3'

services:

  build_worker:
    image: tock/build_worker:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - tock_env=prod
      - JAVA_ARGS=-Xmx1g -XX:MaxMetaspaceSize=256m

  duckling:
    image: tock/duckling:$TAG
    environment:
      - tock_env=prod
    expose:
      - "8080"

  kotlin_compiler:
    image: tock/kotlin_compiler:$TAG
    environment:
      - tock_env=prod
      - tock_kotlin_compiler_classpath=/maven
    expose:
      - "8080"

  admin_web:
    image: tock/bot_admin:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
      - kotlin_compiler
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_bot_admin_rest_default_base_url=http://bot_api:8080
      - tock_bot_compiler_service_url=http://kotlin_compiler:8080
      - tock_configuration_bot_default_base_url=http://bot_api:8080
      #remove this in production
      - tock_https_env=false
      - botadminverticle_body_limit=-1
    ports:
      - "5080:8080"

  nlp_api:
    image: tock/nlp_api:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
    ports:
      - "5081:8080"

  bot_api:
    image: tock/bot_api:$TAG
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - nlp_api
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - tock_nlp_service_url=http://nlp_api:8080
      - tock_env=integ
      - tock_websocket_enabled=true
    ports:
      - "5082:8080"
