version: '3'

volumes:
  tockmongo:
  tockmongo2:
  tockmongo3:

services:

  mongo:
    image: mongo:3.6.5
    volumes:
      - tockmongo:/data/db
    ports:
      - "27017"
    command: --smallfiles --bind_ip_all --port 27017 --replSet "tock"

  mongo2:
    image: mongo:3.6.5
    depends_on:
      - mongo
    volumes:
      - tockmongo2:/data/db
    ports:
      - "27018"
    command: --smallfiles --bind_ip_all --port 27018 --replSet "tock"

  mongo3:
    image: mongo:3.6.5
    depends_on:
      - mongo
      - mongo2
    volumes:
      - tockmongo3:/data/db
    ports:
      - "27019"
    command: --smallfiles --bind_ip_all --port 27019 --replSet "tock"

  mongo-setup:
    container_name: "mongo-setup"
    image: mongo:3.6.5
    depends_on:
      - "mongo"
      - "mongo2"
      - "mongo3"
    links:
      - mongo:mongo
      - mongo2:mongo2
      - mongo3:mongo3
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGO1=mongo
      - MONGO2=mongo2
      - MONGO3=mongo3
      - RS=tock
    entrypoint: [ "/scripts/setup.sh" ]
