version: '3'

services:

  # DEMO

  # demo_api_webhook:
  #   image: tock/bot_api_webhook:$TOCK_TAG
  #   depends_on:
  #     - mongo
  #     - mongo2
  #     - mongo3
  #     - bot_api
  #   environment:
  #     - tock_env=integ
  #   ports:
  #     - "5087:8887"

  demo_api_ws_node:
    build: samples/tock-bot-node
    ports:
      - "5085:8080"

  # demo_open_data_kt:
  #   build: tock-bot-samples
  #   environment:
  #     - tock_env=integ
  #   ports:
  #     - "5089:8887"

  nodered:
    build: ./scripts
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - .:/data
     - ./etc/node-red/.node-red:/home/nodered/.node-red
    environment:
     - NODERED_FLOWS=/data/flows.json
     - NODERED_USERDIR=/home/nodered/.node-red
     - NODERED_SETTINGS=/home/nodered/.node-red/settings.js
     - NODERED_CREDENTIAL_SECRETS=changeme
     - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-changeme}
    env_file:
     - .env