version: '3.7'

networks:
  default:

volumes:
  victoria-metrics-data:
  grafana-data:

services:

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.87.6
    restart: always
    ports:
      - 4428:8428
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    command:
      - "--retentionPeriod=3y"
      # - "--storageDataPath=/storage"

  # grafana:
  #   image: grafana/grafana:9.4.7
  #   restart: always
  #   ports:
  #     - "4000:3000"
  #   volumes:
  #     # - ./etc/grafana:/etc/grafana
  #     # - ./var/lib/grafana:/var/lib/grafana
  #     # - ./var/log/grafana:/var/log/grafana
  #     - grafana-data:/var/lib/grafana
  #     - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
  #     - ./etc/grafana/canvas/:/usr/share/grafana/public/img/bg/:ro
  #   environment:
  #     GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-default}
  #     GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}
  #     GF_INSTALL_PLUGINS: grafana-polystat-panel,volkovlabs-echarts-panel
  #     GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/Tidhome-Power.json
  #     GF_FEATURE_TOGGLES_ENABLE: topnav,newPanelChromeUI
  #   env_file:
  #     - .env

