version: '3.7'

volumes:
  influxdb-data:
  grafana-data:

services:

  influxdb:
    image: influxdb
    # user: "${UID}:${GID}"
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes: 
      - ./etc/influxdb/scripts:/docker-entrypoint-initdb.d
      # - ./var/lib/influxdb:/var/lib/influxdb:rw
      # - ./var/lib/.influx_history:/.influx_history
      - influxdb-data:/var/lib/influxdb:rw
    environment:
      INFLUXDB_DB: "telegraf"
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-default}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-password}
      INFLUXDB_USER: ${INFLUXDB_USER:-default}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-password}
      INFLUXDB_MONITOR_STORE_ENABLED: "false"
      INFLUXDB_META_LOGGING_ENABLED: "true"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"

  telegraf:
    image: telegraf
    network_mode: host
    restart: always
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro      
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc

  grafana:
    image: grafana/grafana
    restart: always
    # user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    volumes:
      # - ./etc/grafana:/etc/grafana
      # - ./var/lib/grafana:/var/lib/grafana
      # - ./var/log/grafana:/var/log/grafana
      - grafana-data:/var/lib/grafana
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-default}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}

  # bootstrap:
  #   image: "alpine:latest"
  #   volumes:
  #     - "./bootstrap.sh:/bootstrap.sh:ro"
  #     - "./etc/grafana/dashboard-system.json:/etc/grafana/dashboard-system.json:ro"
  #   command: /bootstrap.sh

