= Monitoring docker stack

This is an aggregate of many resources out there to run some monitoring stack.

== Simple telegraf + grafana + influxdb

`docker-compose` includes `telegraf`, `grafana` and `influxdb`.

=== Setup

* Initialize using user 1000

[source,bash]
----
$ make init
----

* Start the stack

[source,bash]
----
$ make start
----

* Open your brower to: link:http://localhost:3000/[]
* Use the username/password: __default/password__
* Go to *Data Sources* and add an InfluxDB with host URL: *http://influxdb:8086* and database name *telegraf* (there are for now no credentials)
* Then in *+*, import Dashboard and specify *1443* to import a default *Telegraf* dashboard

=== Use

* Manually create more database:

[source,bash]
----
$ docker-compose exec influxdb influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.6.1
InfluxDB shell 0.9.6.1
> create database SensorData;
...
> show databases;
name: databases
---------------
name
SensorData
telegraf
> 
----

* Test InfluxDB as curl:

[source,bash]
----
$ curl -G http://localhost:8086/query --data-urlencode "q=SHOW DATABASES"
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["telegraf"],["SensorData"]]}]}]}
----

== resources

* link:https://docs.influxdata.com/influxdb/v1.2/introduction/getting_started/[InfluxDB doc]
* link:https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/[InfluxDB doc database retention]
* link:https://devconnected.com/how-to-install-influxdb-telegraf-and-grafana-on-docker/[TIG stack]
* link:https://devconnected.com/the-definitive-guide-to-influxdb-in-2019/[InfluxDB learning]