version: '3.7' 
 
services:

  rasa:
    image: rasa/rasa:1.9.0
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  app:
    build: ./actions
    expose:
      - 5055