= Video - Editing

Below are few applications, links and tips for linux video editing.

== Reviews

* link:https://itsfoss.com/best-video-editing-software-linux/[Video Tools Review]
* link:https://itsfoss.com/linux-photo-management-software/[Photo Tools Review]
* link:https://github.com/leandromoreira/ffmpeg-libav-tutorial[FFMpeg tutorial]

== Tools

* link:https://doc.ubuntu-fr.org/montage_video[Montage Vidéo]
* link:https://github.com/konradit/gopro-linux[GoPro tools]
* link:https://github.com/KonradIT/gopro-py-api[GoPro Python API]
* OpenShot: Install using AppImage

== FUN

* link:https://elder.dev/posts/open-source-virtual-background/[Virtual WebCam]
* link:https://github.com/alyssaq/face_morpher[Face morphing]

== Command lines cheatsheet

=== Resize

link:https://trac.ffmpeg.org/wiki/Scaling%20(resizing)%20with%20ffmpeg[FFMpeg info]

    $ ffmpeg -i input.avi -vf scale=320:240 output.avi

=== Crop

    $ ffmpeg -i /video/Perso/GoPro/GOPR0035.MP4 -strict -2 -vf "crop=1920:1080:150:150" after.mp4

=== Cut From/To

    $ ffmpeg -i input.mkv -ss 00:01:00 -to 00:02:00 -c:v copy -c:a copy output.mp4

=== Stabilize

Basic stabilization:

    $ ffmpeg -i input.mov -vf deshake output.mov

Advanced Stabilization:

* link:https://scottlinux.com/2016/09/17/video-stabilization-using-vidstab-and-ffmpeg-on-linux/[]
* link:https://www.epifocal.net/blog/video-stabilization-with-ffmpeg[]

* link:https://hub.docker.com/r/jrottenberg/ffmpeg/[Example Blog]

    $ docker run -v $(pwd):/tmp/workdir -v /video/Perso/GoPro:/tmp/video jrottenberg/ffmpeg:alpine -i /tmp/video/GOPR0032.MP4 -vf vidstabtransform=input=transform_vectors.trf:zoom=1:smoothing=30,unsharp=5:5:0.8:3:3:0.4 -vcodec libx264 -preset slow -tune film -crf 18 -acodec copy /tmp/workdir/SMOOTH_OUTPUT_VIDEO.mp4

=== Convert to GIF

Convert video to animated GIF:

    $ sudo apt-get install ffmpeg imagemagick
    $ ffmpeg -i input.mp4 -vf scale=480:-1 -r 3 -f image2pipe -vcodec ppm - | convert -delay 20 -loop 0 - output.gif

=== Convert to MP3

Convert video from Webm to MP3:

    $ ffmpeg -i Some-music.webm -vn -ab 128k -ar 44100 -y Some-music.mp3

=== concat

Concat multiple video (useful when kids want to see a bunch of episodes and playlists are not available)

    $ for f in ./*.mp4; do echo "file '$f'" >> mylist.txt; done
    $ ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4

link:https://trac.ffmpeg.org/wiki/Concatenate[Source docs]