= Odroid M1S

link:https://www.hardkernel.com/shop/odroid-m1s-with-8gbyte-ram/[Odroid M1S]

.Specification Hardware
* CPU RK3566: ARM Cortex-A55 with 4 cores
* 8G RAM
* 64G eMMC
* on-board M.2 NVMe slot

.Specification Power
* 1.5-3.5 Watt

== Links

.Hardware Devices
* link:https://wiki.odroid.com/odroid-m1s/odroid-m1s[Odroid M1S Wiki]
** link:https://wiki.odroid.com/accessory/power_supply_battery/m1s_ups[Odroid M1S - UPS]

.Images
* link:https://dn.odroid.com/RK3566/ODROID-M1S/[OS Images Odroid]
* link:https://ppa.linuxfactory.or.kr/images/raw/arm64[OS Images linuxfactory] (search for M1S images)
* link:https://github.com/home-assistant/operating-system/blob/dev/Documentation/boards/hardkernel/odroid-m1s.md[OS Image - Home Assistant]

== Flash OS

* Download image ODROID-M1S_EMMC2UMS.img (3 MB)
* Put in SD slot and power-up. Nothing shows on screen, only blue light shows and nothing else happens.
* Plug USB OTG to computer. Volume should mount like a USB Mass Storage
* Download image debian-bookworm-server-odroidm1s-20240121.img.xz (268 MB)
* Open Etcher, select image, select target, flash
* unplug all, power off, remove SD card
* plug screen, keyboard, power up. OS should boot
* next steps can be done through SSH connection

== Install

.Post-install - password
[source,bash]
----
# with odroid/odroid as default user / password
$ ssh odroid@<ip addr>
# change password right away
$ passwd
# switch sudo to install packages
$ sudo -s
----

.Post-install - Upgrade
[source,bash]
----
$ apt update
$ apt list --upgradable
$ apt upgrade
----

.Post Install - Check-up
[source,bash]
----
# 
root@server:/home/odroid# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

#
root@server:/home/odroid# free -m
              total        used        free      shared  buff/cache   available
Mem:           7678          85        6817          24         776        7489
Swap:             0           0           0

#
root@server:/home/odroid# fdisk -l
...

Device         Boot  Start       End   Sectors  Size Id Type
/dev/mmcblk0p1        6144    530431    524288  256M 83 Linux
/dev/mmcblk0p2      530432 122142719 121612288   58G 83 Linux

# 
root@server:/home/odroid# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           768M  956K  767M   1% /run
/dev/mmcblk0p2   58G  1.4G   54G   3% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/mmcblk0p1  240M   65M  163M  29% /boot
tmpfs           768M     0  768M   0% /run/user/1000
----

.Docker install
[source,bash]
----
# Install steps from https://docs.docker.com/engine/install/ubuntu/
$ apt install ca-certificates curl
$ install -m 0755 -d /etc/apt/keyrings
$ curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
$ chmod a+r /etc/apt/keyrings/docker.asc
$ echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
$ apt update
$ apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Post-install
$ usermod -aG docker odroid

# Tuning
$ vi /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  }
}
$ service docker restart

# reboot here
...
$ docker run hello-world
----

.Tooling
[source,bash]
----
$ apt-get install htop
----

