= Cooking

.Meringue
* 1h15 à 110°C + laisser au four
* 60g de blanc d'oeuf (2 oeufs)
* 60g (120g ?) de sucre poudre blanc
* 1 pincée de sel
* 6 gouttes de jus de citron

* Préchauffer le four, chaleur tournante
* Fouetter à vitesse moyenne jusqu'à ce que cela commence à mousser: Blancs+pincée de sel+jus de citron
* Ajouter la moitier de sucre, et fouetter à vitesse rapide
* Quand le mélange et blanc et brillant, ajouter le reste de sucre
* Fouetter à vitesse rapide jusqu'à ce que le mélange soit ferme et brillant (4-5min)
* Mettre dans une poche à douille, et dresser les meringues sur une plaque avec un peu de farine


== Laits végétaux


.Lait d'avoine maison
* Blender
* Sac à lait végétal
* Bouteille
* 100g de flocon d'avoine
* 1L d'eau bien froide
* 15 à 20g de sirop d'agave

* Verser les flocons d'avoine et l'eau dans le blender
* Mixer 30-60s
* Filtrer avec le sac à lait
* Conserver la pulpe d'avoine (pour des cookies)
* Ajouter du sirop d'agave
* Conserver au frigo

== Cookies

.Cookies flocons d’avoine de base - version okara
* Ingrédients

    2 cuillère à café de levure chimique
    100 g de farine complète
    100 g d'okara de flocons d’avoine
    60 g de sucre en poudre
    50 g de beurre ou huile d'arachide
    60g de pépites de chocolat, ou céréales

* Préparation

    Préchauffez votre four à 180°C/160°C. Recouvrez votre plaque à pâtisserie de papier sulfurisé.
    Dans un bol, tamisez la farine, ajoutez la levure, les flocons d’avoine et le sucre.
    Faites fondre le beurre et ajoutez-le dans le lait dans une casserole et mélangez.
    Ajoutez les ingrédients liquides aux ingrédients secs et mélangez jusqu’à ce que le mélange soit homogène.
    Avec une cuillère à soupe formez des ronds sur une plaque de cuisson en laissant de l’espace entre chaque biscuit.
    Cuisson pendant 10 à 15 minutes jusqu’à ce que les cookies soient dorés.

