version: "3.4"
services:

  # https://quay.io/repository/kiegroup/business-central-workbench
  # open http://localhost:8080/business-central (admin / admin)
  business-central:
    image: quay.io/kiegroup/business-central-workbench-showcase:7.73.0.Final
    hostname: business-central
    environment:
      JAVA_OPTS: "-server -Xms1024m -Xmx1024m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false" 
      # -Dorg.uberfire.nio.git.dir=/var/rules"
    ports:
      - 8080:8080
      - 8001:8001

  # https://quay.io/repository/kiegroup/kie-server-showcase
  # open http://localhost:8180/kie-server (kieserver / kieserver1!)
  # open http://localhost:8180/kie-server/docs/
  kie-server:
    image: quay.io/kiegroup/kie-server-showcase:7.73.0.Final
    hostname: kie-server
    ports:
      - "8180:8080"
      - "8007:8001"
    environment:
      JAVA_OPTS: "-server -Xms1024m -Xmx1024m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false"
      KIE_SERVER_ID: sample-server
      KIE_SERVER_LOCATION: http://kie-server:8080/kie-server/services/rest/server
      KIE_SERVER_CONTROLLER: http://business-central:8080/business-central/rest/controller
      KIE_MAVEN_REPO: http://business-central:8080/business-central/maven2
