version: "3.4"
services:

  # https://quay.io/repository/kiegroup/business-central-workbench
  # open http://localhost:8080/business-central (admin / admin)
  business-central:
    image: quay.io/kiegroup/business-central-workbench-showcase:7.73.0.Final
    hostname: business-central
    environment:
      JAVA_OPTS: "-server -Xms1024m -Xmx1024m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false" 
      # -Dorg.uberfire.nio.git.dir=/var/rules"
    ports:
      - 8080:8080
      - 8001:8001
