= Rules Engine

.References
* link:https://www.mastertheboss.com/bpm/drools/what-is-jboss-drools/[Drools and KIE]

.Guides DMN
* link:https://www.drools.org/learn/dmn.html[DMN]
* link:https://www.youtube.com/watch?v=66vnlOwRamM[Red-Hat tools and concepts]
* link:https://www.youtube.com/watch?v=0hQEMMRVHjA[BMN various types of Rules (Scoring, Classification, etc)]
* link:https://dmn.new[DMN Online editor]

.Guides DRL
* link:https://docs.drools.org/8.32.0.Final/drools-docs/docs-website/drools/introduction/index.html[Drools user Guide]
* link:https://ducmanhphan.github.io/2020-10-20-how-to-use-drools-language-syntax/[DRL syntax]
* link:https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.10/html/developing_decision_services_in_red_hat_decision_manager/drl-rules-con_drl-rules[DRL]
* Examples:
** link:https://github.com/kiegroup/drools/blob/main/drools-examples/src/main/java/org/drools/examples/petstore/PetStoreExample.java[PetStore Java Object Data] and link:https://github.com/kiegroup/drools/blob/main/drools-examples/src/main/resources/org/drools/examples/petstore/PetStore.drl[PetStore DRL]

.Code
* link:https://github.com/jbossdemocentral/kie-server-client-examples[Java KIE example]
* link:https://github.com/nheron/droolsonboarding[Drools Onboarding]
* link:https://github.com/QuickSign/drools-server[Java Drools sample]

* link:https://github.com/signavio/dmn-and-drools-execution-examples/tree/master/src/main/resources[]

== Environment

.Docker:
* link:https://quay.io/repository/kiegroup/business-central-workbench[Business Central workbench] or link:https://quay.io/repository/kiegroup/business-central-workbench-showcase[Business Central Showcase]
* link:https://quay.io/repository/kiegroup/kie-server[KIE Server] or link:https://quay.io/repository/kiegroup/kie-server-showcase[KIE Server Showcase]
* link:https://github.com/jboss-dockerfiles/business-central/tree/main/docker-compose-examples[Full set of deployment] (includes prometheus and grafana)





== Discoveries

.Steps:
* Start env using *make up*
* After ~30s, Open link:localhost:8080/business-central[]
* Create Space and Project, Import sample *traffic-violation*, Test and Deploy

.Refs:
* General Swagger KIE-Server: link:http://localhost:8180/kie-server/docs/[]

.Example requests
[source,bash]
----
# Check deployed containers
$ curl -u kieserver:kieserver1! -X GET "http://localhost:8180/kie-server/services/rest/server/containers" -H "accept: application/json"

# Check specific container
$ curl -u kieserver:kieserver1! -X GET "http://localhost:8180/kie-server/services/rest/server/containers/traffic-violation_1.0.0-SNAPSHOT" -H "accept: application/json"

# Retrieve the openAPI definition for deployed container
$ curl -u kieserver:kieserver1! -X GET "http://localhost:8180/kie-server/services/rest/server/containers/traffic-violation_1.0.0-SNAPSHOT/dmn/openapi.json" -H "accept: application/json" -o openapi.json
----

[IMPORTANT]
====
Open API did not contain Basic Auth, thus was not working.

# https://support.smartbear.com/swaggerhub/docs/tutorials/openapi-3-tutorial.html
# fix URL
  "servers": [ {
    "url" : "http://localhost:8180/kie-server/services/rest"
  } ],
  "security": [
    "BasicAuth": []
  ],
  ...
# fix basic auth
"components" : {
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
       }
     },
     ...
====

.Example deployed files as a jar file
[source,bash]
----
# /opt/jboss/.m2/repository/traffic-violation/traffic-violation/1.0.0-SNAPSHOT/
[jboss@kie-server 1.0.0-SNAPSHOT]$ unzip traffic-violation-1.0.0-SNAPSHOT.jar 
Archive:  traffic-violation-1.0.0-SNAPSHOT.jar
   creating: META-INF/
   creating: META-INF/maven/
   creating: META-INF/maven/traffic-violation/
   creating: META-INF/maven/traffic-violation/traffic-violation/
  inflating: META-INF/maven/traffic-violation/traffic-violation/pom.xml  
  inflating: META-INF/maven/traffic-violation/traffic-violation/pom.properties  
  inflating: META-INF/kmodule.info   
  inflating: META-INF/kmodule.xml    
   creating: META-INF/defaultKieBase/
  inflating: META-INF/defaultKieBase/kbase.cache  
   creating: org/
   creating: org/kie/
   creating: org/kie/example/
   creating: org/kie/example/traffic/
   creating: org/kie/example/traffic/traffic_violation/
  inflating: org/kie/example/traffic/traffic_violation/Traffic Violation.dmn  
   creating: testscenario/
  inflating: testscenario/ScenarioJunitActivatorTest.class  
----


